import { describe, expect, it } from "vitest";
import { deriveBookPageV3, deriveEventShardV3, deriveSeatShardV3 } from "./v3-pdas";

// Golden vectors generated by the public client ABI's web3.js PDA helpers.
// They keep the Worker-native @solana/kit implementation byte-for-byte
// compatible without importing web3.js into the Workers bundle.
const CORE = "11111111111111111111111111111111";

describe("Worker V3 PDA facade", () => {
  it("matches the public client PDA vectors", async () => {
    await expect(deriveBookPageV3(CORE, 1, 8)).resolves.toBe("8wcXqoARAWCKFK1KJCsPsPmgHK4qj9DfJn3R9Hwh2RAc");
    await expect(deriveSeatShardV3(CORE, 3)).resolves.toBe("6tABHuh2EMapJft2HUXPUTGenQvum4vSaJKHnchttAZy");
    await expect(deriveEventShardV3(CORE, 3)).resolves.toBe("67y2o4NsSnyHiNhJDWYDwva5Ydsm56RrRxWGHe86WraY");
  });

  it("rejects caller-controlled invalid shard indexes", async () => {
    await expect(deriveBookPageV3(CORE, 0, 9)).rejects.toThrow("invalid V3 book page");
    await expect(deriveSeatShardV3(CORE, 4)).rejects.toThrow("invalid V3 seat shard");
    await expect(deriveEventShardV3(CORE, -1)).rejects.toThrow("invalid V3 event shard");
  });
});
