export const STOCKSTREAM_PROGRAM_ID = "H3UogXdaamHi4Ga9ZzrZNNttCRpasZgarexVyNTZvGET";

export const STOCKSTREAM_INSTRUCTION = {
  initializeMarket: 0,
  createTraderSeat: 1,
  closeTraderSeat: 2,
  placeOrder: 3,
  cancelOrder: 4,
  cancelAll: 5,
  updateFunding: 6,
  liquidate: 7,
  initializeSettlementScratch: 8,
  initializeVault: 9,
  depositCollateral: 10,
  withdrawCollateral: 11,
  consumeOracleUpdate: 12,
  delegateMarket: 13,
  commitMarket: 14,
  commitAndUndelegate: 15,
  undelegationCallback: 16,
  authorizeTradingSession: 17,
  revokeTradingSession: 18,
  initializeExchange: 19,
  registerStockInstrument: 20,
  createPerpMarket: 21,
  updateStockInstrument: 22,
  suspendStockInstrument: 23,
  updateMarketRisk: 24,
  pauseMarket: 25,
  resumeMarket: 26,
  setCloseOnly: 27,
  enterCorporateAction: 28,
  resolveCorporateAction: 29,
  closeMarket: 30,
  updateTradingSessionLimits: 31,
  closeTradingSession: 32,
  replaceOrder: 33,
  transferToInsuranceFund: 34,
  withdrawProtocolFees: 35,
  withdrawInsuranceFunds: 36,
  recordBadDebt: 37,
  resolveBadDebt: 38,
  reconcileVault: 39,
  updateExchangeConfig: 40,
  delegateClusterMember: 41,
  createMarketAccount: 42,
  createInstrumentAccount: 43,
  createVaultAccount: 44,
  createScratchAccount: 45,
  createV3Account: 46,
} as const;

export const STOCKSTREAM_ACCOUNT_SIZE = 222_752;
export const STOCKSTREAM_TRADING_SESSION_SIZE = 256;
export const STOCKSTREAM_PROGRAM_ID_BYTES = 32;
