#![allow(clippy::too_many_arguments, clippy::type_complexity)] // test helpers
//! Parity with the TypeScript client: fixtures/encoding.json is generated by
//! fixtures/generate.mts from clients/stockstream (the ABI source of truth).

use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde_json::Value;
use stockstream_market_maker::quotes::Side;
use stockstream_market_maker::solana::{b58, pubkey, set_compute_unit_limit, sign_transaction, Keypair};
use stockstream_market_maker::v3::{cancel_order, place_order, replace_order, Bundle, OrderInput};

fn fixture() -> Value {
    serde_json::from_str(include_str!("fixtures/encoding.json")).unwrap()
}
fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
fn unhex(text: &str) -> Vec<u8> {
    (0..text.len()).step_by(2).map(|i| u8::from_str_radix(&text[i..i + 2], 16).unwrap()).collect()
}
fn setup() -> (Value, Keypair, Bundle) {
    let f = fixture();
    let seed: [u8; 32] = unhex(f["seed"].as_str().unwrap()).try_into().unwrap();
    let key = Keypair::from_seed(&seed);
    let program = pubkey("8Ucdsd3ejSEFFTpUivfK84eZv2q6aAe83A9zwSBcxFZ").unwrap();
    let bundle = Bundle::derive(program, pubkey(f["core"].as_str().unwrap()).unwrap(), pubkey(f["snapshot"].as_str().unwrap()).unwrap());
    (f, key, bundle)
}
fn order(seat: u16, side: Side, quantity: u64, price: i64, expires_at: u64, client_order_id: u64, post_only: bool, ioc: bool) -> OrderInput {
    OrderInput { seat, side, quantity, price, expires_at, client_order_id, post_only, immediate_or_cancel: ioc }
}

#[test]
fn bundle_pdas_match_the_client() {
    let (f, key, bundle) = setup();
    assert_eq!(b58(&key.pubkey()), f["authority"]);
    let list = |name: &str| f[name].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect::<Vec<_>>();
    assert_eq!(bundle.book_pages.iter().map(|k| b58(k)).collect::<Vec<_>>(), list("bookPages"));
    assert_eq!(bundle.seat_shards.iter().map(|k| b58(k)).collect::<Vec<_>>(), list("seatShards"));
    assert_eq!(bundle.event_shards.iter().map(|k| b58(k)).collect::<Vec<_>>(), list("eventShards"));
}

#[test]
fn order_instructions_match_the_client_byte_for_byte() {
    let (f, key, bundle) = setup();
    let authority = key.pubkey();
    let order_key: u128 = f["orderKey"].as_str().unwrap().parse().unwrap();
    let place = place_order(&bundle, &authority, &order(3, Side::Ask, 7, 38_012_345, 1_800_000_000, 42, true, false));
    assert_eq!(hex(&place.data), f["place"]);
    let take = place_order(&bundle, &authority, &order(4, Side::Bid, 2, 38_050_000, 1_800_000_060, 43, false, true));
    assert_eq!(hex(&take.data), f["take"]);
    let replace = replace_order(&bundle, &authority, order_key, &order(3, Side::Bid, 5, 38_000_000, 1_800_000_000, 9, true, false));
    assert_eq!(hex(&replace.data), f["replace"]);
    assert_eq!(hex(&cancel_order(&bundle, &authority, 3, order_key).data), f["cancel"]);
    let metas: Vec<Value> = place.accounts.iter().map(|m| serde_json::json!([b58(&m.pubkey), m.is_signer, m.is_writable])).collect();
    assert_eq!(Value::Array(metas), f["metas"]);
}

/// A decoded legacy transaction: header, keys, and each instruction with its accounts resolved.
struct Decoded { header: [u8; 3], keys: Vec<[u8; 32]>, blockhash: [u8; 32], instructions: Vec<([u8; 32], Vec<[u8; 32]>, Vec<u8>)>, signature: [u8; 64], message: Vec<u8> }

fn short_vec(bytes: &[u8], at: &mut usize) -> usize {
    let (mut value, mut shift) = (0usize, 0);
    loop {
        let byte = bytes[*at];
        *at += 1;
        value |= usize::from(byte & 0x7f) << shift;
        if byte & 0x80 == 0 { return value; }
        shift += 7;
    }
}
fn decode(wire: &[u8]) -> Decoded {
    let mut at = 0;
    assert_eq!(short_vec(wire, &mut at), 1);
    let signature: [u8; 64] = wire[at..at + 64].try_into().unwrap();
    at += 64;
    let message = wire[at..].to_vec();
    let header = [wire[at], wire[at + 1], wire[at + 2]];
    at += 3;
    let keys: Vec<[u8; 32]> = (0..short_vec(wire, &mut at)).map(|_| { let k = wire[at..at + 32].try_into().unwrap(); at += 32; k }).collect();
    let blockhash = wire[at..at + 32].try_into().unwrap();
    at += 32;
    let instructions = (0..short_vec(wire, &mut at)).map(|_| {
        let program = keys[wire[at] as usize];
        at += 1;
        let accounts = (0..short_vec(wire, &mut at)).map(|_| { let k = keys[wire[at] as usize]; at += 1; k }).collect();
        let len = short_vec(wire, &mut at);
        let data = wire[at..at + len].to_vec();
        at += len;
        (program, accounts, data)
    }).collect();
    assert_eq!(at, wire.len());
    Decoded { header, keys, blockhash, instructions, signature, message }
}

#[test]
fn signed_transaction_matches_web3js_and_verifies() {
    let (f, key, bundle) = setup();
    let order_key: u128 = f["orderKey"].as_str().unwrap().parse().unwrap();
    let replace = replace_order(&bundle, &key.pubkey(), order_key, &order(3, Side::Bid, 5, 38_000_000, 1_800_000_000, 9, true, false));
    let blockhash = pubkey(f["blockhash"].as_str().unwrap()).unwrap();
    let (wire, signature) = sign_transaction(&key, &[set_compute_unit_limit(600_000), replace], &blockhash).unwrap();
    let ours = decode(&wire);
    let theirs = decode(&unhex(f["transaction"].as_str().unwrap()));

    assert_eq!(ours.header, theirs.header);
    assert_eq!(ours.keys[0], key.pubkey(), "fee payer first");
    let (mut a, mut b) = (ours.keys.clone(), theirs.keys.clone());
    a.sort();
    b.sort();
    assert_eq!(a, b, "same account set");
    assert_eq!(ours.blockhash, theirs.blockhash);
    assert_eq!(ours.instructions, theirs.instructions, "same programs, accounts and data");
    assert_eq!(ours.signature, signature);
    VerifyingKey::from_bytes(&key.pubkey()).unwrap().verify(&ours.message, &Signature::from_bytes(&ours.signature)).unwrap();
    assert!(wire.len() <= 1232);
}
